config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  get 'login' =>  'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'contact_us' => 'enquiries#new'
  get 'contact_us/thanks' => 'enquiries#thanks'
  
  get 'faqs' => 'pages#faq'
  get 'testimonials' => 'pages#testimonials'

  resources :services, only: [:index, :show]
  resources :galleries, only: [:index, :show]

  resources :projects, only: [:index, :show]
  resources :enquiries, only: [:new, :create] do
    collection do
      get :heating_enquiry
      get :tank_enquiry
    end
  end
  resources :sessions, only: [:new, :create]

  namespace :admin do
    root 'projects#index'
    resources :blocks
    resources :services, except: [:show]
    resources :faqs, except: [:show]
    resources :galleries, except: :show do
      resources :gallery_images, only: [:index, :create, :destroy]
    end
    resources :testimonials, except: [:show]
    resources :promotion_cards, except: [:show]
    resources :pages, except: [:show]
    resources :projects, except: [:show]
    resources :enquiries, only: [:index, :show, :destroy]
    resources :users, except: [:show]
  end

  resources :pages, only: [:show], path: '/'


end

app/models/block.rb
class Block < ActiveRecord::Base
  default_scope -> { order id: :asc }
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base

	validates :name, presence: true
	validates :email, presence: true
	validates :phone, presence: true

	enum form_type: [:heating, :oil]

end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  has_many :gallery_images, dependent: :destroy
  mount_uploader :image, GalleryImageUploader

  validates :name, presence: :true

  def preview_thumbs
    gallery_images.shuffle.first(3).collect{|x| x.image}
  end

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base

  belongs_to :gallery
  mount_uploader :image, GalleryImageUploader

  default_scope -> { order('created_at DESC') }

end

app/models/page.rb
class Page < ActiveRecord::Base

	mount_uploader :banner, ImageUploader

	has_many :page_promotions, as: :thing
	has_many :promotion_cards, through: :page_promotions

  def selected_promotions= val
    self.page_promotions.destroy_all
    val.each_value do |card_id|
      page_promotions.create!(promotion_card_id: card_id)
    end
  end

end

app/models/page_promotion.rb
class PagePromotion < ActiveRecord::Base
	default_scope -> { order order: :asc }
	belongs_to :thing, polymorphic: true
	belongs_to :promotion_card

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/promotion_card.rb
class PromotionCard < ActiveRecord::Base


	mount_uploader :image, PromotionImageUploader

end

app/models/service.rb
class Service < ActiveRecord::Base
	


  has_many :page_promotions, as: :thing
  has_many :promotion_cards, through: :page_promotions
  
  mount_uploader :banner, ImageUploader

  def selected_promotions= val
    self.page_promotions.destroy_all
    val.each_value do |card_id|
      page_promotions.create!(promotion_card_id: card_id)
    end
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

  default_scope -> { order date: :desc }

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :remember_token

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,
		presence: true,
		length: {maximum: 255},
		format: {with:  VALID_EMAIL_REGEX},
		uniqueness: { case_sensitive: false}


	has_secure_password
	validates :password, presence: true, length: {minimum:5}, allow_nil: true


	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? 	BCrypt::Engine::MIN_COST :
														BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController

	before_action :set_service, only: [:edit, :update, :destroy]

	def index
		@services = Service.all
	end

	def new
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)
		if @service.save
			flash[:success] = 'Service Created'
			redirect_to @service
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@service.update_attributes(service_params)
		if @service.save
			flash[:success] = 'Service Updated'
			redirect_to @service
		else
			flash[:error] = 'Sorry, an error occured'
			render :edit
		end

	end

	def destroy
		if @service.destroy
			flash[:success] = 'Service Destroyed'
		else
			flash[:error] = 'Sorry, an error occured'
		end
		redirect_to [:admin, :services]

	end

	private

	def service_params
		params.require(:service).permit(:name, :body, :catchline, :banner, selected_promotions: [:first, :second, :third, :fourth])
	end

	def set_service
      @service = Service.find(params[:id])
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin_application'

	before_action :admin_only


	private

		def admin_only
			redirect_to login_path unless logged_in?
		end

	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @page = Page.find_by(path: '')
  end

  def testimonials
    @page = Page.find_by(path: 'testimonials')
    @testimonials = Testimonial.all
  end

  def faq
    @page = Page.find_by(path: 'faq')
  	@faqs = Faq.all
  end

  def show
  	@page = Page.find_by(path: params[:id])
    redirect_to faqs_path if @page.path == 'faq'
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	def index
		@services = Service.all
	end

	def show
		@service = Service.find(params[:id])
		@page = Page.first
	end

end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title title = ''
		if title.blank?
			'Tank Replacement Services'
		else
			"#{title} | Tank Replacement Services"
		end
	end

end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper

	def get_service_promotions
		return Promotions.where('id > ?', 4)
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end


	def current_user
		if user_id = session[:user_id]
			@current_user ||= User.find_by(id: user_id)
		elsif user_id = cookies.signed[:user_id]
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end


	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/admin/services/_form.html.haml
= form_for([:admin, @service]) do |f|

  .field
    = field_set_tag 'banner' do
      - unless @service.new_record? || @service.banner.blank?
        = image_tag(@service.banner)
      = f.file_field :banner
  .field
    = f.label :name
    = f.text_field :name 
  .field
    = f.label :body
    = f.cktext_area :body
  .field
    = f.label :catchline
    = f.text_field :catchline
  = f.fields_for :selected_promotions do |pp|
    .field
      = pp.label :first, 'Promotion Card 1'
      = pp.select :first, PromotionCard.pluck(:name, :id), {selected: @service.promotion_cards.first.try(:id), include_blank: true}
      = f.hidden_field :order, value: 1
    .field
      = pp.label :second, 'Promotion Card 2'
      = pp.select :second, PromotionCard.pluck(:name, :id), {selected: @service.promotion_cards.second.try(:id), include_blank: true}
      = f.hidden_field :order, value: 2
    .field
      = pp.label :third, 'Promotion Card 3'
      = pp.select :third, PromotionCard.pluck(:name, :id), {selected: @service.promotion_cards.third.try(:id), include_blank: true}
      = f.hidden_field :order, value: 3
    .field
      = pp.label :fourth, 'Promotion Card 4'
      = pp.select :fourth, PromotionCard.pluck(:name, :id), {selected: @service.promotion_cards.fourth.try(:id), include_blank: true}
      = f.hidden_field :order, value: 4

  .actions
    = f.submit 'Save'

app/views/admin/services/edit.html.haml
= render 'shared/form_errors', object: @service

= render 'form'

app/views/admin/services/index.html.haml
= link_to 'Create New Service', [:new, :admin, :service], class: 'action_link'
%h1 Services

%table
  %thead
    %tr
      %th
        Name
      %th{'colspan' => 2}
  %tbody
    - @services.each do |service|
      %tr
        %td
          = link_to service.name, service
        %td
          = link_to 'edit', [:edit, :admin, service]
        %td
          = link_to 'delete', [:admin, service], method: 'delete', confirm: 'Are you sure?'

app/views/admin/services/new.html.haml
= render 'shared/form_errors', object: @service

%h1 New Service
= render 'form'

app/views/services/index.html.haml
%table
  %thead
    %tr
      %th
        Name
  %tbody
    - @services.each do |service|
      %tr
        %td
          = link_to service.name, service

app/views/services/show.html.haml
- provide :title, @service.name
= content_for :admin_contextual_links do
  = link_to 'Edit Page', edit_admin_service_path(@service)
- unless @service.banner.blank?
  = image_tag @service.banner.banner, class: 'service_banner'
- if @service.catchline?
  #page_catchline
    = raw @service.catchline
#service_page_container
  #service_content
    %h1= @service.name
    = raw @service.body

    #call_to_action
      For friendly service and a free estimate please call 01362 687 144 or
      = link_to 'click here', new_enquiry_path
      to request a call back

  = render 'shared/promotions_container', page: @service