config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  get 'login' =>  'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'contact_us' => 'enquiries#new'
  get 'contact_us/thanks' => 'enquiries#thanks'
  
  get 'faqs' => 'pages#faq'
  get 'testimonials' => 'pages#testimonials'

  resources :services, only: [:index, :show]
  resources :galleries, only: [:index, :show]

  resources :projects, only: [:index, :show]
  resources :enquiries, only: [:new, :create] do
    collection do
      get :heating_enquiry
      get :tank_enquiry
    end
  end
  resources :sessions, only: [:new, :create]

  namespace :admin do
    root 'projects#index'
    resources :blocks
    resources :services, except: [:show]
    resources :faqs, except: [:show]
    resources :galleries, except: :show do
      resources :gallery_images, only: [:index, :create, :destroy]
    end
    resources :testimonials, except: [:show]
    resources :promotion_cards, except: [:show]
    resources :pages, except: [:show]
    resources :projects, except: [:show]
    resources :enquiries, only: [:index, :show, :destroy]
    resources :users, except: [:show]
  end

  resources :pages, only: [:show], path: '/'


end

app/models/block.rb
class Block < ActiveRecord::Base
  default_scope -> { order id: :asc }
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base

	validates :name, presence: true
	validates :email, presence: true
	validates :phone, presence: true

	enum form_type: [:heating, :oil]

end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  has_many :gallery_images, dependent: :destroy
  mount_uploader :image, GalleryImageUploader

  validates :name, presence: :true

  def preview_thumbs
    gallery_images.shuffle.first(3).collect{|x| x.image}
  end

end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base

  belongs_to :gallery
  mount_uploader :image, GalleryImageUploader

  default_scope -> { order('created_at DESC') }

end

app/models/page.rb
class Page < ActiveRecord::Base

	mount_uploader :banner, ImageUploader

	has_many :page_promotions, as: :thing
	has_many :promotion_cards, through: :page_promotions

  def selected_promotions= val
    self.page_promotions.destroy_all
    val.each_value do |card_id|
      page_promotions.create!(promotion_card_id: card_id)
    end
  end

end

app/models/page_promotion.rb
class PagePromotion < ActiveRecord::Base
	default_scope -> { order order: :asc }
	belongs_to :thing, polymorphic: true
	belongs_to :promotion_card

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/promotion_card.rb
class PromotionCard < ActiveRecord::Base


	mount_uploader :image, PromotionImageUploader

end

app/models/service.rb
class Service < ActiveRecord::Base
	


  has_many :page_promotions, as: :thing
  has_many :promotion_cards, through: :page_promotions
  
  mount_uploader :banner, ImageUploader

  def selected_promotions= val
    self.page_promotions.destroy_all
    val.each_value do |card_id|
      page_promotions.create!(promotion_card_id: card_id)
    end
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

  default_scope -> { order date: :desc }

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :remember_token

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,
		presence: true,
		length: {maximum: 255},
		format: {with:  VALID_EMAIL_REGEX},
		uniqueness: { case_sensitive: false}


	has_secure_password
	validates :password, presence: true, length: {minimum:5}, allow_nil: true


	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? 	BCrypt::Engine::MIN_COST :
														BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin_application'

	before_action :admin_only


	private

		def admin_only
			redirect_to login_path unless logged_in?
		end

	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title title = ''
		if title.blank?
			'Tank Replacement Services'
		else
			"#{title} | Tank Replacement Services"
		end
	end

end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper

	def get_service_promotions
		return Promotions.where('id > ?', 4)
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end


	def current_user
		if user_id = session[:user_id]
			@current_user ||= User.find_by(id: user_id)
		elsif user_id = cookies.signed[:user_id]
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end


	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/admin/pages/_form.html.haml
= form_for([:admin, @page]) do |f|

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :banner
    = f.file_field :banner
  .field
    = f.label :catchline
    = f.text_field :catchline
  .field
    = f.label :body
    = f.cktext_area :body
  = f.fields_for :selected_promotions do |pp|
    .field
      = pp.label :first, 'Promotion Card 1'
      = pp.select :first, PromotionCard.pluck(:name, :id), {selected: @page.promotion_cards.first.try(:id), include_blank: true}
      = pp.hidden_field :order, value: 1
    .field
      = pp.label :second, 'Promotion Card 2'
      = pp.select :second, PromotionCard.pluck(:name, :id), {selected: @page.promotion_cards.second.try(:id), include_blank: true}
      = pp.hidden_field :order, value: 2
    .field
      = pp.label :third, 'Promotion Card 3'
      = pp.select :third, PromotionCard.pluck(:name, :id), {selected: @page.promotion_cards.third.try(:id), include_blank: true}
      = pp.hidden_field :order, value: 3
    .field
      = pp.label :fourth, 'Promotion Card 4'
      = pp.select :fourth, PromotionCard.pluck(:name, :id), {selected: @page.promotion_cards.fourth.try(:id), include_blank: true}
      = f.hidden_field :order, value: 4
  .field
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
= render 'shared/form_errors', object: @page


%h1 Edit Page
= render 'form'

app/views/admin/pages/index.html.haml
= link_to 'Create New Page', [:new, :admin, :page], class: 'action_link'
%h1 Pages


%table
  %thead
    %tr
      %th
        Name
      %th
        Path
      %th{'colspan' => 2}
  %tbody
    - @pages.each do |page|
      %tr
        %td
          = page.name
        %td
          = page.path
        %td
          = link_to 'edit', [:edit, :admin, page]
        %td
          = link_to 'delete', [:admin, page], method: 'delete', confirm: 'Are you sure?'

app/views/admin/pages/new.html.haml
= render 'shared/form_errors', object: @page

%h1 New Page
= render 'form'

app/views/shared/_admin_sidebar.html.haml
#sidebar
  #logo= link_to image_tag('logo.jpg'), root_url
  = link_to 'Services', admin_services_path
  = link_to 'Gallery', admin_galleries_path
  = link_to 'Homepage Blocks', admin_blocks_path
  = link_to 'Faqs', admin_faqs_path
  = link_to 'Pages', admin_pages_path
  = link_to 'Promotion Cards', admin_promotion_cards_path
  = link_to 'Users', admin_users_path
  = link_to 'Enquiries', admin_enquiries_path
  = link_to 'Testimonials', admin_testimonials_path
  .flex_spacer
  = link_to 'Settings', '#', class: ['settings']

app/views/shared/_admin_top_menu.html.haml
#admin_top_nav
  / = link_to 'Home', root_path
  / = link_to 'Admin', admin_root_path
  = yield :admin_contextual_links
  = link_to 'Logout', '/logout', class: 'logout'

app/views/shared/_footer.html.haml
#footer_container
  #logo_panel
    = image_tag 'optec.jpg'
    = image_tag 'af.png'
    = image_tag 'ex.png'
    = image_tag 'ref.png'
    = image_tag 'tt.png'
    = image_tag 'visa.png'

  #footer_catchline
    #footer_catchline_content
      Tank Replacement Services Ltd, Church Farm, Station Road, Wendling,  Dereham, Norfolk,
      %span NR19 2NE
    = link_to 'Email: info@tankreplacementservices.co.uk', 'mailto:info@tankreplacementservices.co.uk'
  #footer_info
    #company_info
      © Copyright 2016, Tank Replacement Services Ltd.

app/views/shared/_form_errors.html.haml
- if object.errors.any?
	.errors_container
		.error_number
			There were 
			= pluralize object.errors.count, 'error'
		%ul
			- object.errors.full_messages.each do |msg|
				%li.error
					= msg

app/views/shared/_header.html.haml
#header_container
  #top_nav
    %span= link_to 'Home', root_url
    %span.menu_spacer
    %span= link_to 'About Us', '/about'
    %span.menu_spacer
    %span= link_to 'Customer Testimonials', '/testimonials'
    %span.menu_spacer
    %span= link_to 'Emergency Help', '/emergency'
    %span.menu_spacer
    %span= link_to 'Heating Service Enquiry', heating_enquiry_enquiries_path
    %span.menu_spacer
    %span= link_to 'Oil Tank Enquiry', tank_enquiry_enquiries_path
    %span.menu_spacer
    %span=link_to 'FAQs', '/faqs'
    %span.menu_spacer
    %span=link_to 'Gallery', galleries_path
    %span.menu_spacer
    %span= link_to 'Contact Us', '/contact_us'

  #header_content
    #header_content_inner


      #phone_numbers
        %div
          #phone_number_area Norfolk
          #phone_number 01362 687144
        #logo= link_to image_tag('logo.jpg'), root_url
        %div
          #phone_number_area Essex
          #phone_number 01206 231555
      #social
        = link_to image_tag('twit.png'), 'https://twitter.com/tankreplacement'
        = link_to image_tag('fb.png'), 'https://www.facebook.com/Tank-Replacement-Services-LTD-1217497121594586/'

  #main_menu
    %span.dropdown
      = link_to 'Plastic Oil Tanks', '#', class: 'blank_link'
      %div
        %span=link_to 'Domestic', '/services/2'
        %span=link_to 'Commercial', '/services/13'

    %span.dropdown
      =link_to 'Steel Oil Tanks', '#', class: 'blank_link'
      %div
        %span=link_to 'Domestic', '/services/5'
        %span=link_to 'Commercial', '/services/6'

    %span=link_to 'Accessories', '/services/11'
    %span=link_to 'Tank Decommission', '/services/12'

    %span.dropdown
      =link_to 'Oil Tank Installations', '#', class: 'blank_link'
      %div
        %span=link_to 'Domestic', '/services/9'
        %span=link_to 'Commercial', '/services/10'
    %span.dropdown
      =link_to 'Fuel Dispensers', '#', class: 'blank_link'
      %div
        %span=link_to 'Plastic', '/services/3'
        %span=link_to 'Steel', '/services/7'

    %span.dropdown
      =link_to 'Heating Services', '#', class: 'blank_link'
      %div
        %span=link_to 'Oil Boiler Servicing and Breakdowns', '/services/14'
        %span=link_to 'Oil boiler Installations', '/services/16'




    %span.menu_toggle_span=link_to 'Menu', 'javascript:void(0)', class: 'menu_toggle'
  #responsive_menu
    .responsive_top_nav
      %span= link_to 'Home', root_url
      %span.menu_spacer
      %span= link_to 'About Us', '/about'
      %span.menu_spacer
      %span= link_to 'Customer Testimonials', '/testimonials'
      %span.menu_spacer
      %span= link_to 'Emergency Help', '/emergency'
      %span.menu_spacer
      %span= link_to 'Heating Service Enquiry', heating_enquiry_enquiries_path
      %span.menu_spacer
      %span= link_to 'Oil Tank Enquiry', tank_enquiry_enquiries_path
      %span.menu_spacer
      %span=link_to 'FAQs', '/faqs'
      %span.menu_spacer
      %span=link_to 'Gallery', galleries_path
      %span.menu_spacer
      %span= link_to 'Contact Us', '/contact_us'
    .responsive_main_menu
      %span.dropdown
      = link_to 'Plastic Oil Tanks', '#', class: 'blank_link'
      %div
        %span=link_to 'Domestic', '/services/2'
        %span=link_to 'Commercial', '/services/13'

      %span.dropdown
        =link_to 'Steel Oil Tanks', '#', class: 'blank_link'
        %div
          %span=link_to 'Domestic', '/services/5'
          %span=link_to 'Commercial', '/services/6'

      %span=link_to 'Accessories', '/services/11'
      %span=link_to 'Tank Decommission', '/services/12'

      %span.dropdown
        =link_to 'Oil Tank Installations', '#', class: 'blank_link'
        %div
          %span=link_to 'Domestic', '/services/9'
          %span=link_to 'Commercial', '/services/10'
      %span.dropdown
        =link_to 'Fuel Dispensers', '#', class: 'blank_link'
        %div
          %span=link_to 'Plastic', '/services/3'
          %span=link_to 'Steel', '/services/7'

      %span.dropdown
        =link_to 'Heating Services', '#', class: 'blank_link'
        %div
          %span=link_to 'Oil Boiler Servicing and Breakdowns', '/services/14'
          %span=link_to 'Oil boiler Installations', '/services/16'

app/views/shared/_promotion_card.html.haml
.promotion{style: "background:#{promotion_card.try(:background)}"}
  - if promotion_card && promotion_card.try(:url).blank?
    = image_tag promotion_card.try(:image)
  - else 
    = link_to image_tag(promotion_card.try(:image)), promotion_card.try(:url)
  .promotion_inner
    %h2= promotion_card.try(:name)
    %p= promotion_card.try(:body)
/= link_to 'More', promotion_card.path if promotion_card.path

app/views/shared/_promotions_container.html.haml
#promotions_container
	- page.page_promotions.each do |promotion|
		= render 'shared/promotion_card', promotion_card: promotion.promotion_card